version: "3"

services:
    mongodb:
        container_name: mongo_db
        image: mongo:6.0.3
        volumes:
            - ./data/db:/data/db
        ports:
            - 27021:27017
        restart: always
        networks:
            - mynetwork
    redis2:
        image: redis:alpine
        container_name: "redis2"
        ports:
            - 6379:6379
        volumes:
            - ./data/redis/data/:/var/lib/redis/
            - ./data/redis/log/:/var/log/redis
        networks:
            - mynetwork
    worker-server:
        container_name: "worker-server"
        build:
            context: worker
            dockerfile: Dockerfile
        ports:
            - 3002:3002
        environment:
            - MONGO_URI=mongodb://mongodb:27017/devops
            - REDIS_URI=redis://redis2:6379
        depends_on:
            - mongodb
            - redis2
        networks:
            - mynetwork
    backend-server:
        container_name: "backend-server"
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - 3001:3001
        environment:
            - MONGO_URI=mongodb://mongodb:27017/devops
            - REDIS_URI=redis://redis2:6379
        depends_on:
            - mongodb
            - redis2
            - worker-server
        networks:
            - mynetwork
    client:
        container_name: "client"
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
            - BACKEND_URI=http://localhost:8000/api
        depends_on:
            - worker-server
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge
